# Generated by Django 4.1.4 on 2022-12-27 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='monto',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='fecha_pago',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='servicio',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='usuario',
            new_name='username',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
