# Generated by Django 4.1.4 on 2023-01-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_user',
            name='payment_state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
