# Generated by Django 4.1.4 on 2022-12-27 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_monto_payments_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='expiration_date',
        ),
    ]
