# Generated by Django 4.1.4 on 2023-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_user_payment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_user',
            name='payment_state',
            field=models.BooleanField(default=False, verbose_name='Estado_pago'),
        ),
    ]
