# Generated by Django 4.1.4 on 2023-01-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_user_payment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_user',
            name='penalty',
            field=models.FloatField(null=True),
        ),
    ]
