# Generated by Django 4.1.4 on 2022-12-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_services_alter_payment_table_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.URLField(max_length=5000),
        ),
    ]
