# Generated by Django 4.1.4 on 2022-12-27 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payments_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='expiration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
