# Generated by Django 4.1.4 on 2022-12-28 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_services_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expired_payments',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expired_payments',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='expired_payments',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='expired_payments',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='expired_payments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
