# Generated by Django 4.1.4 on 2022-12-29 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_expired_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expired_payment',
        ),
    ]
